

python_files = ["tests/*.py"]
plugins = ["tests._plugins.no_skip"]

[tool.pytest.ini_options]
addopts = "-q"
python_files = ["tests/*.py"]

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["pytest", "_pytest.*", "pandas"]
ignore_missing_imports = true
