project: cqo-final
gate:
  csv: data/data_estimates_gate.csv
  features:
  - X0
  - X1
  alpha: 0.05
  w95_max: 10.0
  w99_max: 10.0
  smd_max: 2.0
  mode: order_stat
  alpha_tail: 0.05
  smd_features:
  - X0
  - X1
horizon_days: 90
policy:
  adoption_rule: LCB95 > 0
gates:
  mode: order_stat
  alpha_tail: 0.05
  w95_max: 10.0
  w99_max: 10.0
  smd_max: 2.0
  smd_features:
  - X0
  - X1
runtime:
  out_figures: reports/figures/
  out_tables: reports/tables/
data_contract:
  csv_path: data/data_estimates.csv
  columns:
    y:
      candidates:
      - y
      - profit
      - outcome
      - target
      - revenue
    t:
      candidates:
      - t
      - T
      - treat
      - treatment
      - assigned
      - action
    e:
      candidates:
      - e
      - ps
      - propensity
      - pscore
      - p_hat
    mu0:
      candidates:
      - mu0
      - m0
      - y0_hat
      - mu_0
      - hat_y0
      - pred0
      - predict0
      - out0
    mu1:
      candidates:
      - mu1
      - m1
      - y1_hat
      - mu_1
      - hat_y1
      - pred1
      - predict1
      - out1
t_fallback:
  allow_if_missing: false
  strategy: bernoulli_from_e
mu_fallback:
  allow_if_missing: false
  strategy: global_mean
compare:
  out_dir: reports/compare/
objective:
  primary: GP28
  decision_rule: LCB95>0
pipeline:
  enforce_steps:
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11

observability:
  required_tables:
    - "reports/tables/summary_metrics.csv"
    - "reports/tables/smd_metrics.csv"
    - "reports/tables/estimates.csv"
    - "reports/tables/policy_kpi.csv"
    - "reports/tables/adoption_decision.csv"
  required_columns:
    estimates: ["tau_dr","se_dr","tau_tml","se_tml","lcb95"]
    smd_metrics: ["feature","smd","n0","n1","m0","m1"]

