[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cqo-viz"
version = "0.1.0"
description = "CQO visualization & gates"
requires-python = ">=3.9"
dependencies = [
  "pandas>=2.0",
  "numpy>=1.24",
  "matplotlib>=3.8",
  "click>=8.1",
  "pyyaml>=6.0"
]

[project.scripts]
cqo-viz = "cqo_viz.cli:cli"
