name: CQO Cycle (BASE_1)
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  cycle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install pandas numpy matplotlib pytest pyyaml
      - name: Preflight (SSOT)
        run: python tools/preflight/ssot_guard.py
      - name: Build compare (safe no-op)
        run: |
          mkdir -p reports/{figures,tables,logs} reports/compare/BASE_1/{baseline,new}
          python tools/compare/build_compare_html.py || true
      - name: Tests
        run: pytest -q
