name: CQO Nightly

on:
  schedule:
    - cron: "13 15 * * *"   # 毎日 00:13JST 相当
  workflow_dispatch:

jobs:
  cycle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      - name: Install
        run: python -m pip install -r requirements.txt
      - name: Prepare fixtures (baseline -> reports/tables)
        run: |
          mkdir -p reports/{figures,tables,logs}
          cp -f reports/compare/BASE_1/baseline/summary_metrics.csv  reports/tables/summary_metrics.csv
          cp -f reports/compare/BASE_1/baseline/estimates.csv        reports/tables/estimates.csv
          cp -f reports/compare/BASE_1/baseline/policy_kpi.csv       reports/tables/policy_kpi.csv
          cp -f reports/compare/BASE_1/baseline/adoption_decision.csv reports/tables/adoption_decision.csv
      - name: Run cycle
        env: { COMPARE_BASE: BASE_1 }
        run: ./bin/cqo_cycle.sh
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: cqo-reports-${{ github.run_id }}
          path: |
            reports/index.html
            reports/compare/BASE_1/compare_BASE_1.html
            reports/figures/*
            reports/tables/*
          retention-days: 14
